FromDoppler/unlayer-editor

.eslintrc.json
.prettierrc.json
package.json
src/App.test.tsx
src/App.tsx
src/index.tsx
src/reportWebVitals.ts
src/setupTests.ts
tsconfig.json
yarn.lock

Se configuró prettier y se dio formato al código, tambien se actualizó el script `verify-format`
[DE-243](https://makingsense.atlassian.net/browse/DE-243)

[DE-243] Automatizar validación de Prettier

---

.env.production

Feat: [DE-262](https://makingsense.atlassian.net/browse/DE-262)

DE-262 Definition of base URL and .env files

---

Dockerfile
Jenkinsfile
README.md
package.json
src/App.tsx
src/index.test.tsx

feat: [DE-253](https://makingsense.atlassian.net/browse/DE-253).
Execution in CI environment with failure:
Execution in CI environment with coverage success full:
Execution in local environment with failure:
`yarn coverage:local`
Execution in local environment with coverage success full:
`yarn coverage:local`

DE-253 Add basic configuration for test coverage greater than 80%

---

public/socialShare.js
src/App.tsx

https://user-images.githubusercontent.com/45947909/130259668-3eacbfdd-fc9f-4cba-b166-1e89d692b876.mp4

feat(editor): add social share custom tool with size property

---

.gitignore
config-overrides-dev.js
config-overrides-prod.js
config-overrides.js
package.json
src/App.tsx
webpack.config-dev.js
yarn.lock

Se realizó una doble compilación del bundle, en la primera de minifican los customJs y se copian en la carpeta public, para la segunda se levanta el ambiente como el CRA, se agrego un watch para observar los cambios en el CustomJs y este recompila los customJs para refrescar el ambiente en Dev.
[274](https://makingsense.atlassian.net/browse/DE-274)

[DE-274] Prepara ambiente de desarrollo para proyecto Unlayer

---

.eslintrc.json
config-overrides.js
src/App.tsx
src/customJs/socialShareTool.js
src/customJs/subscribeTool.js
webpack.config-dev.js

Update ESlint configuration to manage undefined variables and any types.

DE-271 update eslint configuration

---

package.json
yarn.lock

It should fix the `yarn start` command.

fix(deps): revert updates of postcss-flexbugs-fixes and webpack-dev-server

---

src/App.tsx
src/external/merge.tags.js

feat: [DE-294](https://makingsense.atlassian.net/browse/DE-294).
Basic configuration to add custom fields from local environment as to `merge tags` options unlayer.
Base documentation [here.](https://docs.unlayer.com/docs/merge-tags)

DE-294 Add merge tags for use as custom fields

---

src/App.tsx
src/customJs/companyTitleDemo/CompanyTitle.js
src/customJs/companyTitleDemo/index.js
src/customJs/index.js
src/customJs/sharedSingletonModule.js

Se agrega un modulo compartido que se inicializa desde el unlayer.init
https://vimeo.com/604894658/7e6a9eb153

[DE-298] Recibir un parámetro arbitrario en el init y renderizarlo en una custom tool

---

webpack.config.js

Ticket: [DE-453](https://makingsense.atlassian.net/browse/DE-453)

DE-453 Typo in webpack config

---

src/customJs/socialShareTool/SocialShareTool.js

Ticket: [DE-453](https://makingsense.atlassian.net/browse/DE-453)

DE-453 Update hrefs with internal custom fields

---

package.json

Use the same fix-format command convention used in other FE projects

---

src/App.tsx

It is to make the test behavior more like the production one

chore: minor changes in test configuration

---

package.json
src/App.tsx
src/customJs/companyTitleDemo/index.js
src/customJs/index.js
src/customJs/localization.js
src/customJs/localization.test.js
src/customJs/socialShareTool/index.js
src/customJs/socialShareTool/index.test.js
src/customJs/socialTool/FacebookProperty.js
src/customJs/socialTool/LinkedInProperty.js
src/customJs/socialTool/SocialTool.js
src/customJs/socialTool/TwitterProperty.js
src/i18n/en.js
src/i18n/es.js
src/i18n/language-tests.test.js
yarn.lock

[DE-564] Intl custom tool

---

package.json
yarn.lock

Update dependencies 2022 05 24b

---

README.md

Related to https://github.com/FromDoppler/mfe-loader/pull/13

DE-666 - Update MFE loader

---

src/index.tsx

chore: show explicit error when root element does not found

---

src/customJs/payuButtonTool/index.js
src/i18n/en.js
src/i18n/es.js

related to: [DE-876](https://makingsense.atlassian.net/browse/DE-876)

[DE-876] translate payu title button

---

src/customJs/index.js
src/customJs/linkProperty.js
src/customJs/payuButtonTool/index.js
src/i18n/en.js
src/i18n/es.js

Added a simple link property for PayU Button tool.
**_Related to:_** [DE-873](https://makingsense.atlassian.net/browse/DE-873)

feat: add link property to payU button tool

---

src/customJs/payuButtonTool/index.js
src/i18n/en.js
src/i18n/es.js

Relates to: [DE-879](https://makingsense.atlassian.net/browse/DE-879)

[DE-879] Rename PayU tool properties section

---

src/customJs/linkProperty.js
src/customJs/payuButtonTool/index.js
src/i18n/en.js
src/i18n/es.js

Related to: [DE-877](https://makingsense.atlassian.net/browse/DE-877)

[DE-877] Help text for button payU properties

---

src/customJs/socialShareTool/index.js
src/i18n/en.js
src/i18n/es.js

Related to: https://makingsense.atlassian.net/browse/DE-892
SPANISH
ENGLISH

[DE-892] Add translation for social share title

---

Dockerfile
package.json
yarn.lock

Combines #582, #592, #593, #595 and #600

Dependencies 2022-12-06

---

src/App.tsx
src/customJs/socialShareTool/SocialShareTool.js
src/customJs/socialShareTool/configuration.js
src/customJs/socialShareTool/enableSocialProperty.test.js
src/customJs/socialShareTool/index.js
src/customJs/socialShareTool/index.test.js
src/i18n/en.js
src/i18n/es.js

fix: https://makingsense.atlassian.net/browse/DE-902
https://user-images.githubusercontent.com/6733401/206265616-f4fd99ac-27e2-44ed-afa1-1057ca3ad5c8.mp4

[DE-902] fix size property to social share tool

---

package.json
src/customJs/commonProperties/linkProperty.js
src/customJs/commonProperties/linkProperty.test.js
src/customJs/commonProperties/unlayerLabelProperty.js
src/customJs/commonProperties/unlayerLabelProperty.test.js
src/customJs/payuButtonTool/index.js
yarn.lock

Keeping the approach used in the https://github.com/FromDoppler/unlayer-editor/pull/616, now we rewrite the LinkProperty component as React component

[DE-882] link property refactor

---

src/customJs/index.js
src/customJs/localization.js

Hi team!
This fixes the issue with image generation (and I have also applied a minimum refactoring).

Ensure compatibility with image generation

---

src/App.tsx

This a minor change but is more consistent code in dev environment when work with Unlayer Editor Extension.

Improvement the use of Unlayer's Type

---

package.json
src/App.tsx
src/customJs/index.js
src/customJs/main.css
webpack.config.js
yarn.lock

Applied the **_inherit_** case for Unlayer tools name.
Related to: [DE-963](https://makingsense.atlassian.net/browse/DE-963)
[DE-963]: https://makingsense.atlassian.net/browse/DE-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DE-963] Build custom css for Unlayer editor

---

src/customJs/main.css

Related to [DE-963](https://makingsense.atlassian.net/browse/DE-963)
[DE-963]: https://makingsense.atlassian.net/browse/DE-963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adjust tool's name when is too long

---

src/customJs/configuration.js
src/customJs/configuration.test.js
src/customJs/index.js
src/customJs/socialShareTool/configuration.js

Hi team!
This is the first step for Promo Code Tool. At the moment, I am only reading the configuration.
The next step will be to render the tool configuration and request the backend for the list of promo codes.

DOP-1396 - Read stores configuration

---

src/App.tsx
src/customJs/components/SocialNetworksWidget.test.js
src/customJs/configuration.js
src/customJs/configuration.test.js
src/customJs/tools/getSocialShareToolDefinition.test.js

I have forgotten to remove this configuration entry in #884

Remove redundant configuration

---

src/customJs/components/UnlayerLabel.tsx
src/customJs/properties/social_networks/SocialNetworksWidget.tsx
src/customJs/properties/social_networks/index.ts
src/customJs/properties/url/UrlWidget.test.js
src/customJs/properties/url/UrlWidget.tsx
src/customJs/properties/url/index.ts
src/customJs/tools/payu_button_tool/index.ts
src/customJs/tools/social_share_tool/index.ts
src/customJs/types.ts
src/customJs/utils/unlayer.tsx

It will be useful to create similar widgets.

Add HOC for adding labels to the widgets

---

src/customJs/components/EmptyViewer.test.js
src/customJs/components/EmptyViewer.tsx
src/customJs/tools/social_share_tool/SocialShareViewer.test.js
src/customJs/tools/social_share_tool/SocialShareViewer.tsx
src/customJs/tools/social_share_tool/index.ts

Create new view for unset components
[DOP-1416](https://makingsense.atlassian.net/browse/DOP-1416)
[DOP-1416]: https://makingsense.atlassian.net/browse/DOP-1416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DOP-1416  - empty viewer

---

src/App.tsx
src/customJs/tools/promo_code/index.test.ts

See https://github.com/MakingSense/MSEditor/blob/e1813fa45ba31ee7ab12406af71f94e714cd84b4/app/constants.js#L205-L217

chore: rename shop names based on MSEditor's constants

---

src/editorsWebappListenersRegistrator.ts
src/index.tsx

chore: render harcoded promo codes for local env

---

src/customJs/tools/promo_code/PromoCodeValues.ts
src/customJs/tools/promo_code/PromoCodeViewer.test.js
src/customJs/tools/promo_code/PromoCodeViewer.tsx

DOP-1421 - set promo code view

---

src/customJs/configuration.ts
src/customJs/properties/helpers.test.ts
src/customJs/properties/helpers.ts
src/customJs/properties/promo_codes/index.ts
src/customJs/tools/promo_code/index.ts
src/customJs/types.ts

Hi team!
This will help to simplify the generation of the tools and it will be a base to define new reusable helpers.

Reusable property helpers

---

src/customJs/properties/promo_codes/PromoCodesWidget.test.js
src/customJs/properties/promo_codes/PromoCodesWidget.tsx

Add a list of radio buttons for select a promo code on the properties panel

DOP-1419 - Add radio button as promo code selector

---

src/customJs/properties/promo_codes/PromoCodesWidget.test.js
src/customJs/properties/promo_codes/PromoCodesWidget.tsx
src/customJs/tools/promo_code/index.ts
src/i18n/en.ts
src/i18n/es.ts

Add message when is not available promo code at the store

DOP-1438 - No promocode available message

---

src/customJs/index.ts

DOP-1439 - Register promocode tool without preview mode

---

src/customJs/properties/promo_codes/PromoCodesWidget.tsx
src/customJs/tools/promo_code/index.ts

- Update icon with transparency
- Reduce widget font size

DOP-1396 - Promo code style fix

---

src/App.tsx
src/customJs/configuration.test.js
src/customJs/configuration.ts

Hi team!
This code will allow us to add links to other Doppler sections. For example, something like this:

Parse external URLs configuration

---

src/customJs/tools/product/ProductViewer.test.jsx
src/customJs/tools/product/ProductViewer.tsx

update html content to render product tool
TODO: refact in case to add new layout
TODO: In case to resolve text rich bug for text format (size and font), remove font and size properties
Bug image
font and size properties

DOP-1451 - Update content viewer for render

---

src/customJs/tools/product/ProductViewer.test.jsx
src/customJs/tools/product/ProductViewer.tsx

replace display flex by block. 
issue: Googles has not support for flex direction
Gmail view

DOP-1485 - resolve visual issue on product tool

---

src/customJs/tools/product/index.test.js
src/customJs/tools/product/index.ts
src/editorsWebappListenersRegistrator.ts

Add transform for:
- Hide discount price when is zero or empty
- Set price default color when discount price is shown

DOP-1485 - Add product tool transform

---

src/customJs/index.ts
src/customJs/properties/product_arrangement/ProductArrangementWidget.test.js
src/customJs/properties/product_arrangement/ProductArrangementWidget.tsx
src/customJs/properties/product_arrangement/index.ts
src/customJs/tools/product/ProductViewer.tsx
src/customJs/tools/product/index.ts
src/customJs/tools/product/layout/layoutPosition01.tsx
src/customJs/tools/product/layout/layoutPosition02.tsx
src/customJs/tools/product/layout/layoutPosition03.tsx
src/customJs/tools/product/layout/layoutPosition04.tsx
src/customJs/tools/product/layout/layoutPosition05.tsx
src/customJs/tools/product/types.ts
src/editorsWebappListenersRegistrator.ts

Add Arragement property to set different way to render the product gallery viewer
Set vertical as default layout
TODO:
update arrangement icon
Uploading product layout.mp4…

DOP-1454 - Add nicer layout

---

src/customJs/tools/product/index.test.js
src/customJs/tools/product/index.ts

Add product description transform to remove HTML tag from a gallery product selected

DOP-1515 - Remove html format for product Description

---

src/customJs/properties/product_arrangement/ProductArrangementWidget.tsx

DOP-1454 - Update nicer layout icon

---

src/App.tsx
src/customJs/tools/dynamic_tool/index.ts

Add multiple dynamic tools for template campaign edition

DOP-1399 - multiple tool for template

---

src/customJs/tools/dynamic_tool/ProductViewer.tsx

Fix text align for dynamic tools

DOP-1401 - resolve text align for other dynamic tools

---

src/customJs/main.css

Fix: update style rules for unlayer 1.9
version on production 
fix version 1.9
fix version 1.5

DOP-1550 - Tool bar style

---

src/customJs/main.css
src/customJs/properties/url/UrlWidget.tsx

Fix: resolve visual issue for input group with unlayer 1.9.0
visual issue:
version 1.5.75
version 1.9.0

DOP-1549 update input group visual style

---

src/customJs/main.css
src/customJs/properties/product_gallery/ProductGalleryWidget.tsx

Fix: update style primary button with unlayer 1.9.0 primary button style
style with version 1.5.9
style with version 1.9.0

DOP-1551 - Resolve primary button visual issue

---

src/customJs/tools/rss/index.ts

DOP-1403 - Update rss icon

---

src/customJs/index.ts

DOP-1403 - Set rss enabled

---

package.json
src/customJs/index.ts
src/customJs/tools/qr/QrViewer.test.jsx
src/customJs/tools/qr/QrViewer.tsx
src/customJs/tools/qr/index.ts
src/customJs/tools/qr/types.ts
src/i18n/en.ts
src/i18n/es.ts
tsconfig.json
yarn.lock

Add QR Tool
QR empty state
QR with url

DOP-1538  - QR tool

---

src/customJs/main.css

Fix input visual issue: the value can not see
Issue:
Fix:

DOP-1549 - fix input visual issue

---

src/customJs/index.ts
src/customJs/properties/qr/QRWidget.tsx
src/customJs/properties/qr/index.ts
src/customJs/properties/qr/types.ts
src/customJs/tools/qr/QrViewer.test.jsx
src/customJs/tools/qr/QrViewer.tsx
src/customJs/tools/qr/index.ts
src/customJs/tools/qr/types.ts
src/editorsWebappListenersRegistrator.ts

fix:
- save image at doppler files
- add widget for save image

DOP-1593 - Save qr image at doppler files

---

src/customJs/properties/promo_codes/PromoCodesWidget.tsx
src/editorsWebappListenersRegistrator.ts

Fix: improve visual list for Promocode component

DOP-1640 - Promocode improve visual list

---

src/customJs/properties/helpers.test.ts
src/customJs/properties/helpers.ts
src/customJs/tools/promo_code/index.test.ts
src/customJs/types.ts

fixes and improves: 
- update widgets with hidden attribute
- update widgets with overrideAllowed attribute
- update borderProperty with default width
- improve autoWidthProperty
- add new types for margin and padding
update unit test
note: this change does not affect the current behavior

DOP-1694 - Update default widgets

---

src/customJs/tools/smartforms/helper.ts
src/customJs/tools/smartforms/index.ts
src/customJs/tools/smartforms/smartFormViewer.tsx
src/customJs/tools/smartforms/types.ts
src/i18n/en.ts
src/i18n/es.ts

Fix: add new action on complete submit for smart forms
https://github.com/user-attachments/assets/aa4e6a98-e1d8-4030-b420-1b061bf1f142

DOP-1705 - Update congrats action for smart form

---

src/customJs/tools/dynamic_tool/ProductViewer.test.jsx
src/customJs/tools/dynamic_tool/ProductViewer.tsx
src/customJs/tools/dynamic_tool/index.ts
src/customJs/tools/dynamic_tool/types.ts

Fix:
Add alignment property to:
- Tittle
- Price
- Info
- Quantity

DOP-1709 - Add alignment property

---

src/customJs/tools/smartforms/index.ts
src/customJs/tools/smartforms/smartFormViewer.tsx

fix:
- Add email field as default input without edit action on it
- Add id on fieldset

DOP-1710 - Add email field as default

---

src/customJs/tools/smartforms/smartFormViewer.tsx

fix: update dynamic type on the input field

Remove hard type on smartform

---

src/customJs/tools/smartforms/helper.ts
src/customJs/tools/smartforms/types.ts
src/i18n/en.ts
src/i18n/es.ts

fix: 
- add close popup option for submit action
- set close action as default
https://github.com/user-attachments/assets/e541eaa1-7f27-472a-9af9-1abb169bcddc

DOP-1714 - Add congrats action

---

src/customJs/tools/dynamic_tool/ProductViewer.tsx

Fix: add some rules to set a determinate height for the image and title
final result

DOP-1713 - add style rule for recommended

---

src/App.tsx
src/customJs/tools/smartforms/helper.ts
src/customJs/tools/smartforms/smartFormViewer.tsx

Fix:
- Adapt country type as dropdown 
- Add field filter (Email)
Render countries on dropdown:
Field email is filtered:

DOP-1715 - Adpat country field

---

src/customJs/tools/dynamic_tool/ProductViewer.tsx
src/customJs/tools/dynamic_tool/index.ts
src/customJs/tools/dynamic_tool/types.ts

Fix: Add height property for the dynamic tool at:
- title 
- price
- quantity
- info

DOP-1721 - Add height property for dynamic tool

---

src/customJs/tools/smartforms/helper.ts
src/customJs/tools/smartforms/index.ts
src/customJs/tools/smartforms/smartFormViewer.tsx
src/customJs/tools/smartforms/types.ts

Fix: 
- Disabled edit field by type
- Hard order for email field
- Disabled remove field for Email
- Add Email field as default on field widget 
https://github.com/user-attachments/assets/421c4a1f-e3b6-4646-86f7-3ff82ac58e00

DOP-1729 - disabled edit field by type

---

src/customJs/tools/smartforms/index.ts

fix: add event at init component

DOP-1729 - fix event listener

---

src/customJs/tools/smartforms/index.ts
src/customJs/tools/smartforms/smartFormViewer.tsx
src/customJs/tools/smartforms/types.ts

fix:
- create new html component for a custom field  boolean and permission
- update element id get by meta data (original doppler field  name)

DOP-1728 - Add switch toggle

---

src/customJs/tools/smartforms/index.ts
src/i18n/en.ts
src/i18n/es.ts

Fix: temporal audit message for no contact list

DOP-1733 - Add validation for no contact list

---

src/customJs/tools/smartforms/smartFormViewer.tsx

Fix: add new data property in the form _data-fields-array-id_ with the name of the custom field used

DOP-1750 - Add array field id

---

src/customJs/components/Modal.tsx

Fix: 
- add a new dynamic action (in this case for the roulette widget to eliminate an segment
- fix typo
- remove unused behavior `onAfterOpen`

DOP-1758 - update modal component

---

src/customJs/index.ts
src/customJs/main.css
src/customJs/properties/button_group/ButtonGroupWidget.tsx
src/customJs/properties/button_group/index.ts

Fix: Add a new tool for selecting a value by button
This component was created to provide a select view as a tab
**TODO**: 
- persist last value
- improve style, for example [Bootstrap Button group](https://getbootstrap.com/docs/5.0/components/button-group/)
- Add logic to work as check or radio (current logic)

DOP-1776 - Add Button radio check group

---

src/customJs/tools/wheel/index.ts
src/customJs/tools/wheel/types.ts
src/customJs/tools/wheel/wheelFortuneViewer.tsx

Fix: Add group panel to switch init and end view
- add validator logic for empty subscription list
- add logic to set email field as first input

DOP-1761 - update init and end view

---

src/customJs/properties/wheel_list/wheelListWidget.tsx

Fix: ad logic to disable the remove action when the segment quantity is less than 3

DOP-1795 - Add logic for remove segment

---

src/customJs/tools/wheel/wheelFortuneViewer.tsx
src/i18n/en.ts
src/i18n/es.ts

fix:
Add a hidden message for you when the user copies the gift code
Add a pointer cursor at 
Remove unused code  for roulette with just a one segment

DOP-1796 - Add copy message

---

src/customJs/properties/wheel_list/index.ts
src/customJs/properties/wheel_list/wheelListWidget.tsx
src/customJs/tools/wheel/index.ts
src/customJs/tools/wheel/types.ts
src/customJs/tools/wheel/wheelFortuneViewer.tsx

Fix:
Add local state for modal date
Update type name from slide to slice
Add border radius to the main roulette container
Add a new wheel style (double border) related to a Figma design

DOP-1791 - Roulette modal fix

---

src/customJs/properties/wheel_list/wheelListWidget.tsx
src/customJs/tools/wheel/wheelFortuneViewer.tsx

Fix: 
- Add padding for congrats and description
- Set font weight for copy message
- Align the chances header to the center at the modal

DOP-1791 - improve visual spaces

---

src/customJs/tools/product/layout/layoutPosition02.tsx
src/customJs/tools/product/layout/layoutPosition03.tsx
src/customJs/tools/product/layout/layoutPosition04.tsx
src/customJs/tools/product/layout/layoutPosition05.tsx

Below I attach screenshots of the different layout positions.
01:
02:
03:
04:
05:

Agregar info values en todos los layout position

---

package-lock.json
package.json
src/App.tsx
src/customJs/tools/product/ProductViewer.test.jsx
src/customJs/tools/product/index.test.js
yarn.lock

- should render dynamic fields with correct data-dc-type attributes
- should NOT render data-dc-type attributes when fields are not dynamic
- should include all info options when productType is dynamic
- should NOT include info options when productType is undefined (defaults to static)
- should transform a product into a dynamic one by adding action, items, and reference

Crear test unitarios sobre producto dinamico

---

src/customJs/properties/wheel_list/wheelListWidget.tsx

Fix:
- resolve max slices logic
- update modal height unit fixed (px) by vertical viewport (vh)

Resolve modal issue
