FromDoppler/unlayer-editor

.gitattributes

Hi @Cromeror, @paangaflo and @maurocardinali, this is to avoid the issue with the .ico file

chore: define .ico files as binary

---

Jenkinsfile
build-n-publish.sh

Hi team, this PR is split into some logical steps on each commit.
I think that the final behavior can be easily understood by reading the last part of  `build-n-publish.sh`.
Could you kindly review it?
---
* git tag: `v12.34.5`
* commit: 2f2ed2d74a43475442fdca142fc8e6696d6a979b
Generated files (not yet):
* `https://cdn.fromdoppler.com/unlayer-editor/asset-manifest-v12.json`
* `https://cdn.fromdoppler.com/unlayer-editor/asset-manifest-v12.34.json`
* `https://cdn.fromdoppler.com/unlayer-editor/asset-manifest-v12.34.5.json`
* `https://cdn.fromdoppler.com/unlayer-editor/asset-manifest-v12.34.5_2f2ed2d74a43475442fdca142fc8e6696d6a979b.json`
* PR #5
* commit: 2f2ed2d74a43475442fdca142fc8e6696d6a979b
Generated files (not yet):
* `https://cdn.fromdoppler.com/unlayer-editor/asset-manifest-pr-5.json …

DE-252 - Generate semantic version numbers

---

Dockerfile
build-n-publish.sh
cdn-helpers/prepare.sh
cdn-helpers/upload.sh

Hi @paangaflo, @maurocardinali, and @Cromeror,
These changes allow us to upload the manifest files using _semantic version_ friendly names.
Here you can view the generated files in the CDN storage:

DE-258- Upload semantic version friendly manifests to CDN

---

.github/dependabot.yml

Dependabot still tries to update Node to v15: https://github.com/FromDoppler/unlayer-editor/pull/19
Maybe this other syntax works better, and if not, at least is cleanest.

chore(deps): configure dependabot to keep using node 14

---

README.md
public/socialTool.js
public/subscribeTool.js
src/App.tsx

Feat: [DE-242](https://makingsense.atlassian.net/browse/DE-242)
El siguiente PR ilustra un ejemplo básico de como agregar múltiples custom tools a través de la opción CustomJS del editor Unlayer. Cada custom tools se agrega de manera independiente en su respetivo archivo JS encapsulando sus propiedades y lógica funcional.
Se agregará los siguientes custom tools:
1. socialTool.js: Es un componente que permite agregar los iconos de Facebook, Twitter y Linkedin para agregar en cada uno de ellos un hypervinculo. Esto se logra creando un properties custom para cada icono. 
2. subscribeTool.js: Es un componente que permite agregar un texto y un link de unsubscribe. Dentro de sus properties permite agregar el link al cual se debe referencia para hacer efectiva el unsubscribe.

DE-242 Basic config to multiple custom tools

---

.editorconfig
.prettierignore

Hi team, 
Prettier and EditorConfig were wrongly validating generated files (`build` and `coverage` folders). I change the configuration to ignore those files or their format.
Also, there are some files that Prettier does not know (`eslintrc.json` and `dependabot.yml`), so I added them to `.prettieringnore` file to hide some wrong warnings.

DE-269 - Format validation fix

---

webpack.config.js

La nueva versión de Webpack va a buscar los assets a:
```
entrypoints: {
main: {
0: "xxxxx.js"
}
}
```
Por esta razón hay que cambiar la estructura del manifest.

fix: update manifest structure

---

src/customJs/localization.js
src/customJs/localization.test.js
src/customJs/socialShareTool/index.test.js
src/i18n/en.js
src/i18n/es.js

It is an example of how to customize Unlayer's default translated messages.
Only pay attention to the last commit, the other ones are part of #311

DE-562 - Customize Unlayer's default translated messages

---

src/App.tsx
src/customJs/index.js

Hi team!
The previous explicit way to initialize the micro-frontend was not working fine due to the asynchronous loading of the assets.
This is the same approach that we use in the other micro-frontends, and it works fine, so, I think it is a good solution, what do you think?

DE-570 - Micro-frontend Initialization

---

src/customJs/index.js

See documentation: https://docs.unlayer.com/docs/link-types
I had to run this code inside the Unlayer's IFrame, for that reason I made the change in [this repository](https://github.com/FromDoppler/unlayer-editor) and not in [Editors WebApp](https://github.com/FromDoppler/doppler-editors-webapp).

fix: remove sms link type

---

src/App.tsx
src/customJs/configuration.test.js
src/customJs/configuration.ts
src/customJs/index.ts
src/customJs/utils/unlayer.tsx

It enables some functionality only when the preview mode configuration is on.

Preview mode configuration

---

src/customJs/properties/social_networks/SocialNetworksWidget.tsx
src/customJs/properties/social_networks/index.ts
src/customJs/properties/url/UrlWidget.tsx
src/customJs/properties/url/index.ts
src/customJs/types.ts
src/customJs/utils/unlayer.tsx

This PR improves the types.
Now, the properties have a complete type tying up the property name and the widget component type. Also, we have types for the parameter `values` (the tool's values) and `data` received by the widget. 
I had to rename the `toolData` property and the `ToolData` type as `toolInfo` and `ToolInfo` to avoid confusion with the `data` property of the tools.

Better types

---

src/customJs/index.ts
src/customJs/utils/unlayer.tsx

Now, the responsibility of adding or not the tool is moved to the definition generation function.

Do not register the tool when the definition is undefined

---

src/customJs/properties/promo_codes/PromoCodesWidget.tsx
src/customJs/properties/promo_codes/types.ts

En este caso la **opcion 3** se encuentra seleccionada (`codigo3`), la cual es de tipo `money` (la **opcion 1** es del mismo tipo, y la **opcion 2** de tipo `percent`):

Dop 1417 treat reponse with promo code items

---

src/customJs/tools/promo_code/index.test.ts
src/customJs/tools/promo_code/index.ts

Add property to set code promotion text style at the viewer
Note: exist a literal `'editor.text_color.label': Color del texto`, but I prefer to add a new: `Color de la fuente`
https://github.com/FromDoppler/unlayer-editor/assets/83654756/e9f9fb49-6c9f-4b1f-8f85-f7aa372d2004

DOP-1420 Set promo code property

---

src/customJs/properties/helpers.test.ts
src/customJs/properties/helpers.ts
src/customJs/properties/url/index.ts
src/customJs/tools/payu_button_tool/index.ts
src/customJs/tools/social_share_tool/index.ts

It will allow us to define the tool without too many details, avoid errors and normalize values.
For example, right now we have an inconsistency in `large` and `big` values, using these helpers will help us to avoid those kinds of issues.
Before:
```js
{
options: {
basic_configuration_section: {
title: intl.formatMessage({ id: 'option_groups.button_options.title' }),
options: {
paymentURL: {
widget: urlPropertyEditor,
data: {
help: PayuButtonHelp(),
},
},
},
size: {
label: intl.formatMessage({ id: '_dp.size' }),
defaultValue: 'medium',
widget: 'dropdown',
data: {
options: [
{
label: intl.formatMessage({ id: '_dp.small' }),
value: 'small',
},
{
label: intl.formatMessage({ id: '_dp.medium' }),
value: 'medium',
},
{
label: intl.formatMessage({ id: '_dp.big' }),
value: 'large',
},
],
},
},
}, …
```

More helpers

---

src/customJs/localization.test.js
src/customJs/localization.ts
src/customJs/properties/helpers.ts
src/customJs/properties/promo_codes/PromoCodesWidget.tsx
src/customJs/properties/promo_codes/index.ts
src/customJs/properties/url/UrlWidget.tsx
src/customJs/tools/payu_button_tool/PayuButtonHelp.tsx
src/customJs/tools/payu_button_tool/PayuButtonViewer.tsx
src/customJs/tools/payu_button_tool/index.ts
src/customJs/tools/promo_code/index.ts
src/customJs/tools/social_share_tool/SocialShareViewer.tsx
src/customJs/tools/social_share_tool/index.ts

This PR adds a new helper `$t` to make `formatMessage` usage more convenient and less verbose.
I am still exposing `intl` because there are more functions, for example:
* `formatDateTimeRange`
* `formatDate`
* `formatTime`
* `formatDateToParts`
* `formatTimeToParts`
* `formatRelativeTime`
* `formatNumber`
* `formatNumberToParts`
* `formatPlural`
* `formatList`
* `formatList`
* `formatListToParts`
* `formatDisplayName`

Translation helper

---

src/customJs/tools/qr/index.ts

Fix: set 240 px as default QR size

DOP-1538 - Set default size value

---

package.json
src/customJs/configuration.test.js
src/customJs/configuration.ts
src/customJs/index.ts
yarn.lock

To use unlayer-editor effectively for popup design, we need to implement optional custom tool configuration at initialization. This allows us to select which tools to activate based on the specific popup widget being edited.

Dph #104 initialize editor

---

src/customJs/index.ts
src/customJs/properties/dynamic_promo_code/DynamicPromoCodeWidget.test.js
src/customJs/properties/dynamic_promo_code/DynamicPromoCodeWidget.tsx
src/customJs/properties/dynamic_promo_code/index.ts
src/customJs/properties/dynamic_promo_code/types.ts
src/customJs/tools/promo_code/PromoCodeViewer.tsx
src/customJs/tools/promo_code/index.test.ts
src/customJs/tools/promo_code/index.ts
src/customJs/tools/promo_code/types.ts
src/editorsWebappListenersRegistrator.ts

Fix: add request to set dynamic Id for replace dynamic content 
[DOP-1661](https://makingsense.atlassian.net/browse/DOP-1661) (Unlayer subtask)
Request object
```
{
"dynamicId": "10102024",
"type": "percent",
"value": "5",
"expire_days": "45",
"min_price": "0",
"prefixe_code": "DOP",
"includes_shipping": false,
"first_consumer_purchase": false,
"combines_with_other_discounts": false
}
```
see  "dynamicId": "10102024" with hardcode
HTML generate by this set
```
<DynamicPromoCode dynamicId="10102024" style="text-align:center;background-color:rgba(255,255,255, 0)" role="container">
<span style="color:#333333;font-size:36px">[[[DC:COUPON_CODE]]]</span>
</DynamicPromoCode>
```
TODO: 
-  Remove previewMode when promotionCodeDynamicEnabled flag is available
[DOP-1661]: …

DOP-1661  - Save dynamic promo code settings

---

src/customJs/tools/promo_code/index.ts
src/i18n/en.ts
src/i18n/es.ts

fix: add validation for undefined dynamic id on promo code tool when it is dynamic

DOP-1647 - Add promocode validator

---

src/customJs/tools/dynamic_tool/ProductViewer.test.jsx
src/customJs/tools/dynamic_tool/ProductViewer.tsx
src/customJs/tools/dynamic_tool/index.ts
src/customJs/tools/dynamic_tool/types.ts
src/customJs/tools/product/ProductViewer.test.jsx
src/customJs/tools/product/ProductViewer.tsx
src/customJs/tools/product/index.ts
src/customJs/tools/product/types.ts

Fix:
Add margin and padding properties for the button at all dynamic tools and product

DOP-1703 - Add padding margin for button

---

src/customJs/tools/smartforms/smartFormViewer.tsx

fix: Move ID to one level up
issue: at each print when hiding the complete field this leaves a space (padding)

DOP-1722 - Update fieldset content

---

src/customJs/tools/dynamic_tool/ProductViewer.test.jsx
src/customJs/tools/dynamic_tool/ProductViewer.tsx
src/customJs/tools/dynamic_tool/index.ts
src/customJs/tools/dynamic_tool/propertyHelper.ts
src/customJs/tools/dynamic_tool/types.ts

Fix: add target property for image link and button link at dynamic product

DOP-1729 - Add target property for link at  dynamic product

---

src/customJs/tools/wheel/index.ts
src/i18n/en.ts
src/i18n/es.ts

fix: add incomplete slide check for roulette widget
TODO: 
- update final content
- add at doppler-popuphub-frontend project audit rule for ROULETTE (hasUnlayerError)

DOP-1763 - Add audit rule for silde incomplete

---

webpack-dev-server.config.js

Bug: renovate update webpack server on pr https://github.com/FromDoppler/unlayer-editor/pull/1542
That change introduces a CORS issue for local files at unlayer settings
fix: add step filter on webpack dev server middleware for cross-origin-header-check
https://github.com/andersk/zulip/commit/2eca9e59ca89dcccca32f39a56bb1517d8474fb2

Resolve local cors issue

---

src/customJs/tools/wheel/wheelFortuneViewer.tsx

With these style changes, we can accommodate long promo codes.

Fix copy icon

---

src/customJs/tools/product/ProductViewer.tsx
src/customJs/tools/product/layout/layoutPosition01.tsx
src/customJs/tools/product/layout/layoutPosition02.tsx
src/customJs/tools/product/layout/layoutPosition03.tsx
src/customJs/tools/product/layout/layoutPosition04.tsx
src/customJs/tools/product/layout/layoutPosition05.tsx

Si ```infoIsDynamic``` no esta presente en values directamente no se agrega el objeto en el ```ProductViewer```. Se estaba agregando de igual forma incluso cuando el producto no era dinámico, no siguiendo la idea planteada en el index.ts de producto donde para agregar info a las options usamos la condicion ```if (isProductTypeDynamic)```.
De esta forma evitamos que intente imprimir valores nulos y se dejara de mostrar ```null``` en productos que **NO** son dinámicos.

Se muestra campo infohtml en productos normales

---

src/customJs/tools/wheel/wheelFortuneViewer.tsx

Se agrega la clase ```dp-click-button``` al boton e icono de copiar del widget de ruleta.

Agregar clase dp-click-button a botones
